### ISSUE TITLE
Exception: sequences different length after alignment

### ISSUE THREAD

**Issue by evanfields** [naobservatory/sequence_tools#3]
Trying to align two sequences which are `<part1><part2>` and `<part2><part1>`. When each part is >= 20bp, I get the following error. I haven't looked at the source to see if there's a simple explanation. Small sample size but no errors when each part is <20bp, ie each sequence is below 40bp.

```
(NAO) Evans-MacBook-Pro:sequence_tools evan$ python --version
Python 3.12.3
(NAO) Evans-MacBook-Pro:sequence_tools evan$ ./align.py GAGGCCCCGGCAAGATACGTATAATGGAGACGTTTCGCCT ATAATGGAGACGTTTCGCCTGAGGCCCCGGCAAGATACGT
Traceback (most recent call last):
  File "/Users/evan/nao/sequence_tools/./align.py", line 329, in <module>
    start()
  File "/Users/evan/nao/sequence_tools/./align.py", line 325, in start
    run(args)
  File "/Users/evan/nao/sequence_tools/./align.py", line 131, in run
    align_and_print(rec1, rec2, args)
  File "/Users/evan/nao/sequence_tools/./align.py", line 209, in align_and_print
    seq1_aligned, seq2_aligned = collapse_subs(alignment, args.max_dist)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evan/nao/sequence_tools/./align.py", line 56, in collapse_subs
    raise Exception(
Exception: sequences different length after alignment: 66 vs 65
```

**Comment by jeffkaufman** [comment]
I think this is downstream from the incredibly hacky implementation of this tool, where instead of using the `alignment.aligned` data structure the way the authors intended I'm parsing the intended-for-humans pretty-printed output.  I should probably just bite the bullet and re-implement this the right way.
